### ISSUE TITLE
NullReferenceException in oss-download

### ISSUE THREAD

**Issue by scovetta** [microsoft/OSSGadget#289]
Running oss-download (0.1.307+9be4e1e55f) on Linux, native version with no parameters gives a NullReferenceExceptoin:

```
root@412946d6c067:/usr/src/app# oss-download --help

   ____   _____ _____    _____           _            _
  / __ \ / ____/ ____|  / ____|         | |          | |
 | |  | | (___| (___   | |  __  __ _  __| | __ _  ___| |_
 | |  | |\___ \\___ \  | | |_ |/ _` |/ _` |/ _` |/ _ \ __|
 | |__| |____) |___) | | |__| | (_| | (_| | (_| |  __/ |_
  \____/|_____/_____/   \_____|\__,_|\__,_|\__, |\___|\__|
                                            __/ |
                                           |___/
OSS Gadget - oss-download 0.1.307+9be4e1e55f - github.com/Microsoft/OSSGadget
oss-download 0.1.307+9be4e1e55f
© Microsoft Corporation. All rights reserved.
USAGE:
Download the given package:
  oss-download --download-directory . [options] package-url...

  -x, --download-directory        (Default: .) the directory to download the package to.
  -m, --download-metadata-only    (Default: false) download only the package metadata, not the package.
  -e, --extract                   (Default: false) Extract the package contents
  -c, --use-cache                 (Default: false) do not download the package if it is already present in the destination directory.
  --help                          Display this help screen.
  --version                       Display version information.

The package-url specifier is described at https://github.com/package-url/purl-spec:
  pkg:cargo/rand                The latest version of Rand (via crates.io)
  pkg:cocoapods/AFNetworking    The latest version of AFNetworking (via cocoapods.org)
  pkg:composer/Smarty/Smarty    The latest version of Smarty (via Composer/ Packagist)
  pkg:cpan/Apache-ACEProxy      The latest version of Apache::ACEProxy (via cpan.org)
  pkg:cran/ACNE@0.8.0           Version 0.8.0 of ACNE (via cran.r-project.org)
  pkg:gem/rubytree@*            All versions of RubyTree (via rubygems.org)
  pkg:golang/sigs.k8s.io/yaml   The latest version of sigs.k8s.io/yaml (via proxy.golang.org)
  pkg:github/Microsoft/DevSkim  The latest release of DevSkim (via GitHub)
  pkg:hackage/a50@*             All versions of a50 (via hackage.haskell.org)
  pkg:maven/org.apdplat/deep-qa The latest version of org.apdplat.deep-qa (via repo1.maven.org)
  pkg:npm/express               The latest version of Express (via npm.org)
  pkg:nuget/Newtonsoft.JSON     The latest version of Newtonsoft.JSON (via nuget.org)
  pkg:pypi/django@1.11.1        Version 1.11.1 of Django (via pypi.org)
  pkg:ubuntu/zerofree           The latest version of zerofree from Ubuntu (via packages.ubuntu.com)
  pkg:vsm/MLNET/07              The latest version of MLNET.07 (from marketplace.visualstudio.com)
  pkg:url/foo@1.0?url=<URL>     The direct URL <URL>
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CST.OpenSource.DownloadTool.RunAsync(Options options) in /home/vsts/work/1/s/src/oss-download/DownloadTool.cs:line 74
   at Microsoft.CST.OpenSource.DownloadTool.Main(String[] args) in /home/vsts/work/1/s/src/oss-download/DownloadTool.cs:line 69
   at Microsoft.CST.OpenSource.DownloadTool.<Main>(String[] args)
Aborted
```

**Comment by gfs** [comment]
@scovetta is this specific to linux? Will investigate this week.
