### ISSUE TITLE
.vhdx Extraction failing

### ISSUE THREAD

**Issue by daalcant** [microsoft/OSSGadget#88]
.vhdx extraction tests are failing and have been disabled. 

First failed pipeline run I see is from commit [3e781fa75d948e438668c08be834ed3b98f2f780](https://github.com/microsoft/OSSGadget/commit/3e781fa75d948e438668c08be834ed3b98f2f780).

### ExtractArchive (Shared.vhdx,True)
Test method Microsoft.CST.OpenSource.Tests.ExtractorTests.ExtractArchive threw exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at DiscUtils.Streams.WrappingMappedStream\`1.get_Length()
   at DiscUtils.Streams.SubStream..ctor(Stream parent, Int64 first, Int64 length)
   at DiscUtils.Partitions.GuidPartitionTable.Open(GptEntry entry)
   at DiscUtils.Partitions.GuidPartitionInfo.Open()
   at DiscUtils.PhysicalVolumeInfo.Open()
   at DiscUtils.LogicalVolumeInfo.Open()
   at DiscUtils.FileSystemManager.DetectFileSystems(VolumeInfo volume)
   at Microsoft.CST.OpenSource.MultiExtractor.Extractor.DumpLogicalVolume(LogicalVolumeInfo volume, String parentPath, Boolean parallel, FileEntry parent)+MoveNext() in d:\a\1\s\src\MultiExtractor\Extractor.cs:line 1269
   at Microsoft.CST.OpenSource.MultiExtractor.Extractor.ExtractVHDXFile(FileEntry fileEntry, Boolean parallel)+MoveNext() in d:\a\1\s\src\MultiExtractor\Extractor.cs:line 478
   at Microsoft.CST.OpenSource.MultiExtractor.Extractor.ExtractFile(String filename, Boolean parallel)+MoveNext() in d:\a\1\s\src\MultiExtractor\Extractor.cs:line 211
   at System.Collections.Generic.List\`1..ctor(IEnumerable\`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable\`1 source)
   at Microsoft.CST.OpenSource.Tests.ExtractorTests.ExtractArchive(String fileName, Boolean parallel, Int32 expectedNumFiles) in d:\a\1\s\src\tests\ExtractorTests.cs:line 58

### ExtractArchive (Shared.vhdx,False)
Test method Microsoft.CST.OpenSource.Tests.ExtractorTests.ExtractArchive threw exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at DiscUtils.Streams.WrappingMappedStream\`1.get_Length()
   at DiscUtils.Streams.SubStream..ctor(Stream parent, Int64 first, Int64 length)
   at DiscUtils.Partitions.GuidPartitionTable.Open(GptEntry entry)
   at DiscUtils.Partitions.GuidPartitionInfo.Open()
   at DiscUtils.PhysicalVolumeInfo.Open()
   at DiscUtils.LogicalVolumeInfo.Open()
   at DiscUtils.FileSystemManager.DetectFileSystems(VolumeInfo volume)
   at Microsoft.CST.OpenSource.MultiExtractor.Extractor.DumpLogicalVolume(LogicalVolumeInfo volume, String parentPath, Boolean parallel, FileEntry parent)+MoveNext() in d:\a\1\s\src\MultiExtractor\Extractor.cs:line 1269
   at Microsoft.CST.OpenSource.MultiExtractor.Extractor.ExtractVHDXFile(FileEntry fileEntry, Boolean parallel)+MoveNext() in d:\a\1\s\src\MultiExtractor\Extractor.cs:line 478
   at Microsoft.CST.OpenSource.MultiExtractor.Extractor.ExtractFile(String filename, Boolean parallel)+MoveNext() in d:\a\1\s\src\MultiExtractor\Extractor.cs:line 211
   at System.Collections.Generic.List\`1..ctor(IEnumerable\`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable\`1 source)
   at Microsoft.CST.OpenSource.Tests.ExtractorTests.ExtractArchive(String fileName, Boolean parallel, Int32 expectedNumFiles) in d:\a\1\s\src\tests\ExtractorTests.cs:line 58

**Comment by gfs** [comment]
I'll take a look today.
